/**
 * Tipos de ação registrados em LOGAUDITORIA (Quadro 40 do DERS).
 */
const TipoAcao = Object.freeze({
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  UPLOAD_VISTA_EXPLODIDA: "UPLOAD_VISTA_EXPLODIDA",
  EXTRACAO_IA: "EXTRACAO_IA",
  VALIDACAO_HITL: "VALIDACAO_HITL",
  CRIACAO_USUARIO: "CRIACAO_USUARIO",
  EDICAO_USUARIO: "EDICAO_USUARIO",
  ATIVAR_DESATIVAR_USUARIO: "ATIVAR_DESATIVAR_USUARIO",
  ALTERACAO_SENHA: "ALTERACAO_SENHA",
  EDICAO_REGISTRO: "EDICAO_REGISTRO",
  EXCLUSAO_REGISTRO: "EXCLUSAO_REGISTRO",
  CRIACAO_EMPRESA: "CRIACAO_EMPRESA",
  ATIVAR_DESATIVAR_EMPRESA: "ATIVAR_DESATIVAR_EMPRESA",
  ACESSO_NAO_AUTORIZADO: "ACESSO_NAO_AUTORIZADO",
  ARQUIVAMENTO_DOCUMENTO: "ARQUIVAMENTO_DOCUMENTO",
});

module.exports = { TipoAcao };
